// This file is auto-generated by the `generate_imports.ts` script.
// Do not edit it manually, unless you know your concept requires a custom instantiation procedure.

import { SyncConcept } from "@engine";

export const Engine = new SyncConcept();

import { testDb } from "@utils/database.ts";

import PlaylistConcept from "./Playlist/PlaylistConcept.ts";
import MusicDiscoveryConcept from "./MusicDiscovery/MusicDiscoveryConcept.ts";
import FriendingConcept from "./Friending/FriendingConcept.ts";
import ProfileConcept from "./Profile/ProfileConcept.ts";
import RequestingConcept from "./Requesting/RequestingConcept.ts";
import ReviewConcept from "./Review/ReviewConcept.ts";
import UserAuthenticationConcept from "./UserAuthentication/UserAuthenticationConcept.ts";
import SessionConcept from "./Session/SessionConcept.ts";

export type { default as PlaylistConcept } from "./Playlist/PlaylistConcept.ts";
export type { default as MusicDiscoveryConcept } from "./MusicDiscovery/MusicDiscoveryConcept.ts";
export type { default as FriendingConcept } from "./Friending/FriendingConcept.ts";
export type { default as ProfileConcept } from "./Profile/ProfileConcept.ts";
export type { default as RequestingConcept } from "./Requesting/RequestingConcept.ts";
export type { default as ReviewConcept } from "./Review/ReviewConcept.ts";
export type { default as UserAuthenticationConcept } from "./UserAuthentication/UserAuthenticationConcept.ts";
export type { default as SessionConcept } from "./Session/SessionConcept.ts";

// Initialize the database connection
export const [db, client] = await testDb();

export const Playlist = Engine.instrumentConcept(new PlaylistConcept(db));
export const MusicDiscovery = Engine.instrumentConcept(new MusicDiscoveryConcept(db));
export const Friending = Engine.instrumentConcept(new FriendingConcept(db));
export const Profile = Engine.instrumentConcept(new ProfileConcept(db));
export const Requesting = Engine.instrumentConcept(new RequestingConcept(db));
export const Review = Engine.instrumentConcept(new ReviewConcept(db));
export const UserAuthentication = Engine.instrumentConcept(new UserAuthenticationConcept(db));
export const Session = Engine.instrumentConcept(new SessionConcept(db));
